---

- hosts: all
  become: true
  tasks:

  - name: Remove apache2 package
    apt:
      name: apache2
      state: absent

  - name: Remove PHP support for apache
    apt:
      name: libapache2-mod-php
      state: absent

# To run: `ansible-playbook --ask-become-pass remove_apache.yml`